### PR TITLE
Respect the tax exempt flag on b2b account

### PR DESCRIPTION
**Pull request by jyucis**
Checks for the installation for b2b plugin and creates zero dollar
price adjustments for tax exempt organizations

TAXJAR-1

### CODE REVIEW

**Review by bencrouse — APPROVED** [review]

**Comment by bencrouse** [comment]
Looks good, I added the access token secret, and rerunning build to get a green.

**Comment by bencrouse** [comment]
So @jyucis looks like this depends on circuit breaker - do we still want that, and if so any reason to not move that to GitHub?

**Comment by bencrouse** [comment]
@jyucis you see my last comment?

**Comment by bencrouse** [comment]
Rerunning build since circuit breaker is in the wild now...

**Comment by tubbo** [comment]
This has been marked as a draft PR so it can't be merged until workarea-commerce/workarea-taxjar#2 is merged into master. Tests seem OK here when I rebase it with my branch that fixes all the tests broken in master, but I still need to do the rebasing locally, as we touched some of the same files.

**Pull request merged**
